### PR TITLE
Full page screenshot support + advanced screenshot functions

### PR DESCRIPTION
**Pull request by xinaiz**
So, many webdriver users myself included often struggle not be able to take full page screenshots. That should solve it.

Using simple:
```java
open("http://jkorpela.fi/www/testel.html");
takeFullPageScreenshot("jkorpela");
```

We can get:
test1

Note that this is not magic. This function scrolls each time by the height of viewport and makes sub-screenshots, and then merges them. If you try to make full-page screenshot of for example YouTube or Yahoo pages, the top navigation bar will follow viewport upon scrolling down, thus screenshot will not be valid and look like this:

youtube

This is not tested on all browsers though. So far works fine with Chrome and Firefox.

# EDIT 1/31/2018
Added three new functions:
- scrollToCenter
- takeScreenshotOf
- takeScreenshotWithHighlight

> public static void scrollToCenter(WebElement webElement)

This function tries to center webElement in the viewport. For now it's main use is for `takeScreenshotWithHighlight`, because classic `scrollTo` function will scroll just enough for element to appear, often leaving it on the very bottom or the top of the viewport.

> public static void takeScreenshotOf(WebElement element, String fileName)

Instead of taking screen of full viewport, this function creates image only of the target webElement. Thus, if webElement is bound by rect of size 50x150, the image will have size of 50x150

Example:
```java
open("http://jkorpela.fi/www/testel.html");
WebElement elem = driver().findElement(By.xpath("/html/body/h1"));
takeScreenshotOf(elem, "elementScreenshot");
```

Result:
elementscreenshot

> public static void takeScreenshotWithHighlight(WebElement element, int borderWidth, Color highlightColor, int borderOffset, String fileName)

This function (with various overloads) allows to take screenshot of the viewport with the target webElement in the center (if possible - if element is at the very top of the page or the bottom, it will not be in the center of image). The target webElement will be highlighted with default or custom border. By default border is 1 pixel wide and of color red. User can also specify if surrounding rectangle should be bigger or smaller by passing `borderOffset` value.

Example 1:
```java
open("http://jkorpela.fi/www/testel.html");
WebElement elem = driver().findElement(By.xpath("/html/body/h3[1]"));
takeScreenshotWithHighlight(elem, "highlightScreenshot1");
```

Result:
highlightscreenshot1

Example 2:
```java
open("http://jkorpela.fi/www/testel.html");
WebElement elem = driver().findElement(By.xpath("/html/body/blockquote/p"));
takeScreenshotWithHighlight(elem, 5, Color.MAGENTA, 5, "highlightScreenshot2");
```
Result:
highlightscreenshot2

### CODE REVIEW

**Comment by andidev** [comment]
Great, ill try release this tonight

**Comment by xinaiz** [comment]
Added some new screenshot functions to the pull request

**Comment by andidev** [comment]
Great!

**Comment by andidev** [comment]
Released in 3.10.0!

**Pull request merged**
